replicas: 1
provider: azure
azure:
  cloud: "AzurePublicCloud"
  resourceGroup: "dns-resource-group"
  tenantId: "<tenantdId>"
  subscriptionId: "<subscriptionId>"
  aadClientId: "<aadClientId>"
  aadClientSecret: "<aadClientSecret>"
  useManagedIdentityExtension: false

domainFilters:
  - iaclab.com.br

rbac:
  create: true
