controller:
  replicaCount: 2
  publishService:
    enabled: true
  ingressClass: nginx-internal
  service:
    loadBalancerIP: 10.1.47.0
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "PrivateSubnet"
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "staging"
  config:
    use-forwarded-headers: "true"
  extraArgs:
    default-ssl-certificate: "sre/default-tls"
#  dns_local: rabbitmq.dev.svc.cluster.local