apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: stg

---

apiVersion: v1
kind: Namespace
metadata:
  name: prd

---

apiVersion: v1
kind: Namespace
metadata:
  name: sre

---

apiVersion: v1
kind: Namespace
metadata:
  name: drone

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: drone

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: drone-deploy
rules:
  - apiGroups: ["extensions","apps",""]
    resources: ["deployments","secrets","services","ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drone-deploy
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone
roleRef:
  kind: ClusterRole
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io